use actix_cors::Cors;
use actix_web::{web, App, HttpServer, HttpResponse};
use serde::{Deserialize, Serialize};

#[derive(Deserialize)]
struct RenderRequest {
    markdown: Option<String>,
    run_id: Option<String>,
    title: Option<String>,
    papers: Option<u32>,
    claims: Option<u32>,
    conflicts: Option<u32>,
    duration: Option<u32>,
}

#[derive(Serialize)]
struct HealthResponse {
    status: String,
    service: String,
    version: String,
}

fn markdown_to_typst(req: &RenderRequest) -> String {
    let title = req.title.clone().unwrap_or("Clinical Agent Report".to_string());
    let run_id = req.run_id.clone().unwrap_or("—".to_string());
    let papers = req.papers.unwrap_or(0);
    let claims = req.claims.unwrap_or(0);
    let conflicts = req.conflicts.unwrap_or(0);
    let duration = req.duration.unwrap_or(0);
    let now = chrono::Utc::now().format("%Y-%m-%d %H:%M UTC").to_string();

    let body = if let Some(md) = &req.markdown {
        md.lines().map(|line| {
            if line.starts_with("## ") {
                format!("== {} ==\n", &line[3..])
            } else if line.starts_with("# ") {
                format!("= {} =\n", &line[2..])
            } else if line.starts_with("- ") {
                format!("- {}\n", &line[2..])
            } else if line.is_empty() {
                "\n".to_string()
            } else {
                format!("{}\n", line)
            }
        }).collect::<String>()
    } else {
        "No content provided.".to_string()
    };

    let red    = "#ef4444";
    let gray1  = "#71717a";
    let gray2  = "#27272a";
    let gray3  = "#52525b";
    let dark   = "#111113";
    let green  = "#22c55e";
    let white  = "white";

    let run_id_short = &run_id[..run_id.len().min(36)];

    format!(
r#"#set page(paper: "a4", margin: (x: 2.5cm, y: 2.5cm))
#set text(font: "Liberation Sans", size: 11pt)

#align(center)[
  #text(size: 22pt, weight: "bold")[Clinical Agent]
  #linebreak()
  #text(size: 14pt, fill: rgb("{red}"))[Pipeline Execution Report]
  #linebreak()
  #text(size: 10pt, fill: rgb("{gray1}"))[ {now} ]
]

#line(length: 100%, stroke: rgb("{red}"))
#v(0.5cm)

#grid(
  columns: (1fr, 1fr, 1fr, 1fr),
  gutter: 1em,
  rect(fill: rgb("{dark}"), radius: 4pt, inset: 12pt)[
    #text(size: 8pt, fill: rgb("{gray1}"))[PAPERS]\
    #text(size: 24pt, weight: "bold", fill: {white})[{papers}]
  ],
  rect(fill: rgb("{dark}"), radius: 4pt, inset: 12pt)[
    #text(size: 8pt, fill: rgb("{gray1}"))[CLAIMS]\
    #text(size: 24pt, weight: "bold", fill: {white})[{claims}]
  ],
  rect(fill: rgb("{red}"), radius: 4pt, inset: 12pt)[
    #text(size: 8pt, fill: {white})[CONFLICTS]\
    #text(size: 24pt, weight: "bold", fill: {white})[{conflicts}]
  ],
  rect(fill: rgb("{dark}"), radius: 4pt, inset: 12pt)[
    #text(size: 8pt, fill: rgb("{gray1}"))[DURATION]\
    #text(size: 24pt, weight: "bold", fill: rgb("{green}"))[ {duration}s ]
  ],
)

#v(0.5cm)
#text(size: 9pt, fill: rgb("{gray3}"))[Run ID: {run_id_short}]
#line(length: 100%, stroke: rgb("{gray2}"))
#v(0.3cm)

{body}

#v(1cm)
#line(length: 100%, stroke: rgb("{gray2}"))
#align(center)[
  #text(size: 8pt, fill: rgb("{gray3}"))[
    Generated by clinical-agent v3.0 · Maliki Mayzar · Zero Budget. Full Power.
  ]
]
"#,
        red = red, gray1 = gray1, gray2 = gray2, gray3 = gray3,
        dark = dark, green = green, white = white,
        now = now, papers = papers, claims = claims,
        conflicts = conflicts, duration = duration,
        run_id_short = run_id_short, body = body,
    )
}

async fn render_pdf(req: web::Json<RenderRequest>) -> HttpResponse {
    let typst_src = markdown_to_typst(&req);

    match compile_typst(&typst_src) {
        Ok(pdf_bytes) => {
            HttpResponse::Ok()
                .content_type("application/pdf")
                .append_header(("Content-Disposition", "attachment; filename=\"clinical-agent-report.pdf\""))
                .body(pdf_bytes)
        }
        Err(e) => {
            HttpResponse::InternalServerError()
                .json(serde_json::json!({"error": e}))
        }
    }
}

fn compile_typst(source: &str) -> Result<Vec<u8>, String> {
    let tmp_dir = std::path::PathBuf::from(std::env::var("HOME").unwrap_or("/tmp".to_string()));
    let src_path = tmp_dir.join("report.typ");
    let out_path = tmp_dir.join("report.pdf");

    std::fs::write(&src_path, source)
        .map_err(|e| format!("Write error: {}", e))?;

    let output = std::process::Command::new("typst")
        .arg("compile")
        .arg(&src_path)
        .arg(&out_path)
        .output()
        .map_err(|e| format!("Typst not found: {}", e))?;

    if !output.status.success() {
        return Err(format!("Typst error: {}", String::from_utf8_lossy(&output.stderr)));
    }

    let pdf = std::fs::read(&out_path)
        .map_err(|e| format!("Read error: {}", e))?;

    Ok(pdf)
}

async fn health() -> HttpResponse {
    HttpResponse::Ok().json(HealthResponse {
        status: "ok".to_string(),
        service: "report-exporter".to_string(),
        version: "0.1.0".to_string(),
    })
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    tracing_subscriber::fmt::init();
    let port = std::env::var("PORT").unwrap_or("8004".to_string());
    let addr = format!("0.0.0.0:{}", port);
    println!("[report-exporter] Starting on {}", addr);

    HttpServer::new(|| {
        let cors = Cors::default()
            .allow_any_origin()
            .allow_any_method()
            .allow_any_header();

        App::new()
            .wrap(cors)
            .route("/health", web::get().to(health))
            .route("/render", web::post().to(render_pdf))
    })
    .bind(&addr)?
    .run()
    .await
}